/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/tailwind.config`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/sendpulse`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EventsCardComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WealthHorizontalCardScroll`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EventRead`; params?: Router.UnknownInputParams; } | { pathname: `/../types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/tailwind.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/sendpulse`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EventsCardComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WealthHorizontalCardScroll`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EventRead`; params?: Router.UnknownOutputParams; } | { pathname: `/../types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/tailwind.config${`?${string}` | `#${string}` | ''}` | `/../lib/sendpulse${`?${string}` | `#${string}` | ''}` | `/../components/EventsCardComponent${`?${string}` | `#${string}` | ''}` | `/../components/WealthHorizontalCardScroll${`?${string}` | `#${string}` | ''}` | `/../components/EventRead${`?${string}` | `#${string}` | ''}` | `/../types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/tailwind.config`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/sendpulse`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EventsCardComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WealthHorizontalCardScroll`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EventRead`; params?: Router.UnknownInputParams; } | { pathname: `/../types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
